AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cruddur Serverless Parent Template

Parameters:
  DatabaseUrl:
    Type: String
    Description: PostgreSQL connection string
    Default: "postgresql://cruddur:password@localhost:5432/cruddur"

Resources:
  # DynamoDB + Message Stream Stack
  DynamoDBMessagingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/dynamo-stream-template.yaml

  # Post Email Confirm Stack
  PostEmailConfirmStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/post-email-template.yaml
      Parameters:
        DatabaseUrl: !Ref DatabaseUrl

  # Process Images Stack
  ProcessImagesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/process-images.yaml
      Parameters:
        ThumbingBucketName: "assets.cruddur.jawid.me"

Outputs:
  PostConfirmationFunctionArn:
    Description: "Post Confirmation Lambda Function ARN"
    Value: !GetAtt PostEmailConfirmStack.Outputs.PostConfirmationFunctionArn
    Export:
      Name: CruddurPostConfirmationLambdaArnV2

  MessageStreamFunctionArn:
    Description: "Message Stream Lambda Function ARN"
    Value: !GetAtt DynamoDBMessagingStack.Outputs.MessageStreamFunctionArn
    Export:
      Name: CruddurMessageStreamLambdaArnV2

  MessagesTableName:
    Description: "Messages DynamoDB Table Name"
    Value: !GetAtt DynamoDBMessagingStack.Outputs.MessagesTableName
    Export:
      Name: CruddurMessagesTableNameV2

  ConversationsTableName:
    Description: "Conversations DynamoDB Table Name"
    Value: !GetAtt DynamoDBMessagingStack.Outputs.ConversationsTableName
    Export:
      Name: CruddurConversationsTableNameV2
