AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cruddur Serverless Parent Template

Parameters:
  DatabaseUrl:
    Type: String

  AssetsBucketName:
    Type: String
    Default: assets.cruddur.jawid.me

  AvatarUploadPrefix:
    Type: String
    Default: avatar/original/

  CreateAssetsBucket:
    Type: String
    AllowedValues: ["true", "false"]
    Default: "false"

  FrontendOrigin:
    Type: String
    Default: https://cruddur.jawid.me

  CognitoUserPoolId:
    Type: String
    Default: eu-west-2_Jwi9THX3b

  CognitoUserPoolClientId:
    Type: String
    Default: 1ls5p1vu83m5ahseab36ufk6vm

  CorsAllowedOrigins:
    Type: String
    Default: "https://cruddur.jawid.me,http://localhost:3000,https://localhost:3000"

Resources:
  # Messaging + WebSocket tables and handlers
  DynamoDBMessagingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: services/dynamo-stream/template.yaml

  # User bootstrap after Cognito confirm
  PostEmailConfirmStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: services/cognito-post-confirmation/template.yaml
      Parameters:
        DatabaseUrl: !Ref DatabaseUrl

  # 🔑 KEEP THIS LOGICAL ID
  # Avatar upload + resize + DB update
  ProcessImagesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: services/avatar-processing/template.yaml
      Parameters:
        AssetsBucketName: !Ref AssetsBucketName
        CreateAssetsBucket: !Ref CreateAssetsBucket
        CorsAllowedOrigins: !Ref CorsAllowedOrigins
        DatabaseUrl: !Ref DatabaseUrl

  AvatarUploadStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: services/avatar-presign/template.yaml
      Parameters:
        AvatarBucketName: !Ref AssetsBucketName
        AvatarUploadPrefix: !Ref AvatarUploadPrefix
        FrontendOrigin: !Ref FrontendOrigin
        UserPoolId: !Ref CognitoUserPoolId
        UserPoolClientId: !Ref CognitoUserPoolClientId

Outputs:
  PostConfirmationFunctionArn:
    Description: "Post Confirmation Lambda Function ARN"
    Value: !GetAtt PostEmailConfirmStack.Outputs.PostConfirmationFunctionArn
    Export:
      Name: CruddurPostConfirmationLambdaArnV2

  MessageStreamFunctionArn:
    Description: "Message Stream Lambda Function ARN"
    Value: !GetAtt DynamoDBMessagingStack.Outputs.MessageStreamFunctionArn
    Export:
      Name: CruddurMessageStreamLambdaArnV2

  MessagesTableName:
    Description: "Messages DynamoDB Table Name"
    Value: !GetAtt DynamoDBMessagingStack.Outputs.MessagesTableName
    Export:
      Name: CruddurMessagesTableNameV2

  ConversationsTableName:
    Description: "Conversations DynamoDB Table Name"
    Value: !GetAtt DynamoDBMessagingStack.Outputs.ConversationsTableName
    Export:
      Name: CruddurConversationsTableNameV2

  AvatarUploadApiUrl:
    Description: "HTTP API endpoint for presigned avatar uploads"
    Value: !GetAtt AvatarUploadStack.Outputs.AvatarUploadApiUrl
    Export:
      Name: CruddurAvatarUploadApiUrl
