AWSTemplateFormatVersion: 2010-09-09

Description: |
  Static frontend hosting
  - CloudFront Distribution with Origin Access Control
  - Uses existing S3 bucket (named by RootDomainName)
  - Route53 alias record to CloudFront

Parameters:
  CertificateArn:
    Type: String

  RootDomainName:
    Type: String
    Description: Frontend domain (cruddur.jawid.me)
    Default: cruddur.jawid.me

  HostedZoneId:
    Type: String
    Description: Route53 hosted zone ID for jawid.me

Resources:
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}OAC"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  RootBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RootDomainName
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${RootDomainName}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution}"
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource:
              - !Sub "arn:aws:s3:::${RootDomainName}/*"
              - !Sub "arn:aws:s3:::${RootDomainName}"
            Condition:
              Bool:
                aws:SecureTransport: false

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: Frontend React for Cruddur
        DefaultRootObject: index.html
        HttpVersion: http2and3
        Aliases:
          - !Ref RootDomainName
        Origins:
          - Id: RootBucketOrigin
            DomainName: !Sub "${RootDomainName}.s3.${AWS::Region}.amazonaws.com"
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !GetAtt OriginAccessControl.Id
        DefaultCacheBehavior:
          TargetOriginId: RootBucketOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
        CustomErrorResponses:
          # Route SPA paths back to index so client-side router can handle them
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only

  CruddurAliasRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "${RootDomainName}."
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront hosted zone ID
        DNSName: !GetAtt Distribution.DomainName
        EvaluateTargetHealth: false
Outputs:
  RootBucketName:
    Value: !Ref RootDomainName
    Export:
      Name: !Sub "${AWS::StackName}RootBucketName"

  DistributionId:
    Value: !Ref Distribution
    Export:
      Name: !Sub "${AWS::StackName}DistributionId"

  DistributionDomainName:
    Value: !GetAtt Distribution.DomainName
    Export:
      Name: !Sub "${AWS::StackName}DistributionDomainName"
