AWSTemplateFormatVersion: 2010-09-09

Description: |
  Static frontend hosting
  - CloudFront Distribution with Origin Access Control
  - S3 bucket for root domain
  - S3 bucket for www redirect

Parameters:
  CertificateArn:
    Type: String

  RootDomainName:
    Type: String
    Description: Naked domain (eg. cruddur.com)



Resources:
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}OAC"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  RootBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RootDomainName
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${RootDomainName}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution}"
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource:
              - !Sub "arn:aws:s3:::${RootDomainName}/*"
              - !Sub "arn:aws:s3:::${RootDomainName}"
            Condition:
              Bool:
                aws:SecureTransport: false

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: Frontend React for Cruddur
        DefaultRootObject: index.html
        HttpVersion: http2and3
        Aliases:
          - !Ref RootDomainName
        Origins:
          - Id: RootBucketOrigin
            DomainName: !Sub "${RootDomainName}.s3.${AWS::Region}.amazonaws.com"
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !GetAtt OriginAccessControl.Id
        DefaultCacheBehavior:
          TargetOriginId: RootBucketOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
Outputs:
  RootBucketName:
    Value: !Ref RootDomainName
    Export:
      Name: !Sub "${AWS::StackName}RootBucketName"

  DistributionDomainName:
    Value: !GetAtt Distribution.DomainName
    Export:
      Name: !Sub "${AWS::StackName}DistributionDomainName"
