AWSTemplateFormatVersion: '2010-09-09'

Description: This template creates a free tier DynamoDB table for Cruddur messages.

Parameters:
  TableName:
    Type: String
    Description: Name of the DynamoDB table
    Default: cruddur-messages

Resources:
  # Create a free tier DynamoDB table
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      # Define the attributes that will be used for the primary key.
      AttributeDefinitions:
        - AttributeName: "message_group_uuid"
          AttributeType: "S" # S for String
        - AttributeName: "created_at"
          AttributeType: "S" # S for String (using ISO 8601 format)

      # Define the primary key schema.
      # 'message_group_uuid' is the Partition Key (HASH)
      # 'created_at' is the Sort Key (RANGE)
      KeySchema:
        - AttributeName: "message_group_uuid"
          KeyType: "HASH"
        - AttributeName: "created_at"
          KeyType: "RANGE"

      # Use PROVISIONED billing mode to stay within the free tier limits.
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 25  #within the 25 free RCUs
        WriteCapacityUnits: 25 #within the 25 free WCUs

      # Enable Point-in-Time Recovery for data protection (recommended).
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

      # Enable server-side encryption (recommended for security).
      SSESpecification:
        SSEEnabled: true

Outputs:
  DynamoDBTableName:
    Description: "The name of the DynamoDB table"
    Value: !Ref DynamoDBTable
    Export:
      Name: !Sub "${AWS::StackName}-DynamoDBTableName"

  DynamoDBTableArn:
    Description: "The ARN of the DynamoDB table"
    Value: !GetAtt DynamoDBTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}-DynamoDBTableArn"
