AWSTemplateFormatVersion: 2010-09-09


Description: ECS for  running flask from ecr

Resources:
  Type: AWS::ECS::TaskDefinition
  Properties:
    ContainerDefinitions: 
      - ContainerDefinition
    Cpu: String
    EnableFaultInjection: Boolean
    EphemeralStorage: 
      EphemeralStorage
    ExecutionRoleArn: String
    Family: String
    IpcMode: String
    Memory: String
    NetworkMode: String
    PidMode: String
    PlacementConstraints: 
      - TaskDefinitionPlacementConstraint
    ProxyConfiguration: 
      ProxyConfiguration
    RequiresCompatibilities: 
      - String
    RuntimePlatform: 
      RuntimePlatform
    Tags: 
      - Tag
    TaskRoleArn: String
    Volumes: 
      - Volume


Outputs:
