AWSTemplateFormatVersion: '2010-09-09'


Description: AWS CloudFormation template to create an RDS PostgreSQL database instance.


Parameters:
  DBUserName:
    Type: String
    Default: cruddur
    Description: Database user name
    NoEcho: true
  DBPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: Database admin password
 

Resources:
  PostgreSQL:
    Type: AWS::RDS::DBInstance
    Properties: 
      # Basic Database Configuration
      Engine: "postgres"
      EngineVersion: "15.4"
      DBInstanceClass: "db.t3.micro"
      DBInstanceIdentifier: cruddur-db-dev
      DBName: cruddur-app
      
      # Authentication
      MasterUsername: !Ref DBUserName
      MasterUserPassword: !Ref DBPassword
      
      # Storage Configuration
      AllocatedStorage: 20
      StorageType: "gp2"
      StorageEncrypted: true
      
      # Network & Security
      AvailabilityZone: "eu-west-2a"
      Port: "5432"
      PubliclyAccessible: true #only for dev
      
      # Maintenance & Updates
      AllowMajorVersionUpgrade: true
      ApplyImmediately: true
      PreferredMaintenanceWindow: "sun:04:00-sun:05:00"
      PreferredBackupWindow: "03:00-04:00"  # When to backup (daily) (free)
      BackupRetentionPeriod: 7               # How many days to keep backups
  
      # Advanced Configuration
      DeletionProtection: true
      Timezone: "UTC"
      UseDefaultProcessorFeatures: true
      EnablePerformanceInsights: true
      PerformanceInsightsRetentionPeriod: 7  # Free tier (7 days)
      # # Tags
      # Tags: 
      #   - Tag
    

Outputs:
  StackName:
    Description: The name of the current stack
    Value: !Sub ${AWS::StackName}
    Export:
      Name: !Sub '${AWS::StackName}-StackName'

  DatabaseName:
    Description: The name of the database
    Value: !Ref PostgreSQL
    Export:
      Name: !Sub '${AWS::StackName}-DatabaseName'