AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image processing stack (avatars, thumbnails, SNS events)

Globals:
  Function:
    Runtime: python3.13
    Timeout: 30
    MemorySize: 512

Parameters:
  AssetsBucketName:
    Type: String
    Default: assets.cruddur.jawid.me

  CreateAssetsBucket:
    Type: String
    AllowedValues: ["true", "false"]
    Default: "false"
    Description: Create S3 bucket only if it does not already exist

  CorsAllowedOrigins:
    Type: String
    Default: "https://cruddur.jawid.me,http://localhost:3000,https://localhost:3000"

  DatabaseUrl:
    Type: String
    Description: PostgreSQL connection string

Conditions:
  ShouldCreateBucket: !Equals [!Ref CreateAssetsBucket, "true"]

Resources:
  # ------------------------------------------------------------
  # OPTIONAL S3 BUCKET
  # ------------------------------------------------------------
  AssetsBucket:
    Type: AWS::S3::Bucket
    Condition: ShouldCreateBucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref AssetsBucketName
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: [GET, PUT, HEAD]
            AllowedOrigins: !Split [",", !Ref CorsAllowedOrigins]
            MaxAge: 3000

  # ------------------------------------------------------------
  # SNS TOPIC
  # ------------------------------------------------------------
  AvatarEventsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: cruddur-avatar-events

  # ------------------------------------------------------------
  # THUMBNAIL GENERATOR (S3 notification configured OUTSIDE SAM)
  # ------------------------------------------------------------
  ThumbnailLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: image-to-thumbnail
      CodeUri: ../functions/image-to-thumbnail/
      Handler: app.lambda_handler
      Environment:
        Variables:
          THUMBING_BUCKET_NAME: !Ref AssetsBucketName
          THUMBING_S3_FOLDER_INPUT: avatar/original/
          THUMBING_S3_FOLDER_OUTPUT: avatar/processed/
          THUMBING_TOPIC_ARN: !Ref AvatarEventsTopic
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref AssetsBucketName
        - S3WritePolicy:
            BucketName: !Ref AssetsBucketName
        - SNSPublishMessagePolicy:
            TopicName: cruddur-avatar-events

  # ------------------------------------------------------------
  # SNS → DATABASE CONSUMER
  # ------------------------------------------------------------
  AvatarDbConsumer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: avatar-db-consumer
      CodeUri: ../functions/avatar-db-consumer/
      Handler: app.lambda_handler
      Environment:
        Variables:
          ASSETS_BASE_URL: !Sub "https://${AssetsBucketName}"
          DATABASE_URL: !Ref DatabaseUrl
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        AvatarEvents:
          Type: SNS
          Properties:
            Topic: !Ref AvatarEventsTopic

Outputs:
  AssetsBucketName:
    Value: !Ref AssetsBucketName

  AvatarEventsTopicArn:
    Value: !Ref AvatarEventsTopic
    Export:
      Name: CruddurAvatarEventsTopicArn
