AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: |
  Cognito post-confirmation Lambda
  - Creates user record after email confirmation

Globals:
  Function:
    Runtime: python3.13
    Timeout: 30

Parameters:
  DatabaseUrl:
    Type: String
    Description: PostgreSQL connection string

  LogRetentionInDays:
    Type: Number
    Default: 30

Resources:
  PostConfirmationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/post-email-confirm
      RetentionInDays: !Ref LogRetentionInDays

  PostConfirmationFunction:
    Type: AWS::Serverless::Function
    DependsOn:
      - PostConfirmationLogGroup
    Properties:
      FunctionName: post-email-confirm
      CodeUri: post-email-confirm-function/
      Handler: app.lambda_handler
      Description: Creates user record after Cognito email confirmation
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl

Outputs:
  PostConfirmationFunctionArn:
    Description: Post confirmation Lambda ARN
    Value: !GetAtt PostConfirmationFunction.Arn
