AWSTemplateFormatVersion: 2010-09-09
Description: |
  Minimal CI/CD pipeline for frontend
  - GitHub source
  - CodeBuild for React build
  - S3 deployment
  - CloudFront invalidation

Parameters:
  GitHubBranch:
    Type: String
    Default: prod

  GithubRepo:
    Type: String
    Default: Jawidd/aws-project

  FrontendBucketName:
    Type: String
    Description: S3 bucket name for frontend hosting

  CloudFrontDistributionId:
    Type: String
    Description: CloudFront distribution ID for frontend

Resources:




  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"

              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub "arn:aws:s3:::cfn-artifacts-${AWS::AccountId}-${AWS::Region}/*"
                  - !Sub "arn:aws:s3:::${FrontendBucketName}/*"

              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetBucketLocation
                Resource:
                  - !Sub "arn:aws:s3:::cfn-artifacts-${AWS::AccountId}-${AWS::Region}"
                  - !Sub "arn:aws:s3:::${FrontendBucketName}"

              - Effect: Allow
                Action:
                  - cloudfront:CreateInvalidation
                Resource: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistributionId}"

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${AWS::StackName}-build"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: FRONTEND_BUCKET
            Value: !Ref FrontendBucketName
          - Name: CLOUDFRONT_DISTRIBUTION_ID
            Value: !Ref CloudFrontDistributionId
      Cache:
        Type: S3
        Location: !Sub "cfn-artifacts-${AWS::AccountId}-${AWS::Region}/codebuild-cache"
      Source:
        Type: CODEPIPELINE
        BuildSpec: frontend-react-js/buildspec.yml

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:GetBucketVersioning
                Resource:
                  - !Sub "arn:aws:s3:::cfn-artifacts-${AWS::AccountId}-${AWS::Region}"
                  - !Sub "arn:aws:s3:::cfn-artifacts-${AWS::AccountId}-${AWS::Region}/*"

              - Effect: Allow
                Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                Resource: !GetAtt CodeBuildProject.Arn

              - Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                Resource: arn:aws:codeconnections:eu-west-2:225442939245:connection/b774dde0-c8da-4d70-8c29-69959959fc25

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Sub "cfn-artifacts-${AWS::AccountId}-${AWS::Region}"
      Stages:
        - Name: Source
          Actions:
            - Name: GitHub
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              OutputArtifacts:
                - Name: Source
              Configuration:
                ConnectionArn: arn:aws:codeconnections:eu-west-2:225442939245:connection/b774dde0-c8da-4d70-8c29-69959959fc25
                FullRepositoryId: !Ref GithubRepo
                BranchName: !Ref GitHubBranch

        - Name: Build
          Actions:
            - Name: BuildAndDeploy
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: Source
              Configuration:
                ProjectName: !Ref CodeBuildProject

Outputs:
  PipelineName:
    Value: !Ref Pipeline


