AWSTemplateFormatVersion: 2010-09-09

Description: |
  CI/CD pipeline
  - GitHub source
  - CodeBuild image bake
  - ECS service deploy

Parameters:
  GitHubBranch:
    Type: String
    Default: prod

  GithubRepo:
    Type: String
    Default: omenking/aws-bootcamp-cruddur-2023

  ClusterStack:
    Type: String

  ServiceStack:
    Type: String

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub "cruddur-cicd-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled

  CodeBuildBakeImageStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: nested/codebuild-bake.yaml

  CodeStarConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: !Sub "${AWS::StackName}-github"
      ProviderType: GitHub

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHub
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '2'
              OutputArtifacts:
                - Name: Source
              Configuration:
                ConnectionArn: !Ref CodeStarConnection
                FullRepositoryId: !Ref GithubRepo
                BranchName: !Ref GitHubBranch

        - Name: Build
          Actions:
            - Name: BakeImage
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: Source
              Configuration:
                ProjectName:
                  Fn::GetAtt:
                    - CodeBuildBakeImageStack
                    - Outputs.CodeBuildProjectName

        - Name: Deploy
          Actions:
            - Name: ECSDeploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: ECS
                Version: '1'
              InputArtifacts:
                - Name: ImageDefinition
              Configuration:
                ClusterName:
                  Fn::ImportValue: !Sub "${ClusterStack}ClusterName"
                ServiceName:
                  Fn::ImportValue: !Sub "${ServiceStack}ServiceName"
