AWSTemplateFormatVersion: 2010-09-09

Description: |
  Static frontend hosting
  - CloudFront Distribution
  - S3 bucket for root domain
  - S3 bucket for www redirect
  - Route53 alias records

Parameters:
  CertificateArn:
    Type: String

  HostedZoneName:
    Type: String
    Description: Public hosted zone (eg. cruddur.com)

  RootDomainName:
    Type: String
    Description: Naked domain (eg. cruddur.com)

  WwwDomainName:
    Type: String
    Description: WWW domain (eg. www.cruddur.com)

Resources:
  RootBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref RootDomainName
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  WWWBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref WwwDomainName
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref RootDomainName

  RootBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RootBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${RootBucket}/*"
            Principal: '*'

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: Frontend React for Cruddur
        DefaultRootObject: index.html
        HttpVersion: http2and3
        Aliases:
          - !Ref RootDomainName
          - !Ref WwwDomainName
        Origins:
          - Id: RootBucketOrigin
            DomainName: !GetAtt RootBucket.DomainName
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: RootBucketOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only

  RootDomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${HostedZoneName}."
      Name: !Sub "${RootDomainName}."
      Type: A
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  WwwDomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${HostedZoneName}."
      Name: !Sub "${WwwDomainName}."
      Type: A
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
