AWSTemplateFormatVersion: 2010-09-09
Description: |
  CodeBuild project used for baking container images
  - CodeBuild Project
  - CodeBuild IAM Role
  - CloudWatch Log Group

Parameters:
  ProjectName:
    Type: String
    Default: cruddur-bake-image

  LogGroupPath:
    Type: String
    Default: /cruddur/codebuild/bake-service

  LogStreamName:
    Type: String
    Default: backend-flask

  CodeBuildImage:
    Type: String
    Default: aws/codebuild/amazonlinux2-x86_64-standard:4.0

  CodeBuildComputeType:
    Type: String
    Default: BUILD_GENERAL1_SMALL

  CodeBuildTimeoutMins:
    Type: Number
    Default: 10

  BuildSpec:
    Type: String
    Default: backend-flask/buildspec.yml

  ArtifactBucketName:
    Type: String
    Description: S3 bucket used by CodePipeline for build input and output artifacts

Resources:
  CodeBuildLogGroup:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref LogGroupPath
      RetentionInDays: 30

  CodeBuildRole:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}Role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${ProjectName}ECR"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:PutImage
                  - ecr:BatchGetImage
                  - ecr:GetDownloadUrlForLayer
            Resource: '*'
        - PolicyName: !Sub "${ProjectName}Logs"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${LogGroupPath}:*"
        - PolicyName: !Sub "${ProjectName}Artifacts"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                Resource: !Sub "arn:aws:s3:::${ArtifactBucketName}/*"
              - Effect: Allow
                Action:
                  - s3:GetBucketLocation
                  - s3:ListBucket
                Resource: !Sub "arn:aws:s3:::${ArtifactBucketName}"

  CodeBuildProject:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      ServiceRole: !GetAtt CodeBuildRole.Arn
      TimeoutInMinutes: !Ref CodeBuildTimeoutMins
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: !Ref CodeBuildComputeType
        Image: !Ref CodeBuildImage
        Type: LINUX_CONTAINER
        PrivilegedMode: true
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: !Ref LogGroupPath
          StreamName: !Ref LogStreamName
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref BuildSpec

Outputs:
  CodeBuildProjectName:
    Value: !Ref CodeBuildProject
