AWSTemplateFormatVersion: 2010-09-09
Description: |
  CodeBuild project used for baking container images
  - CodeBuild Project
  - CodeBuild IAM Role
  - CloudWatch Log Group

Parameters:
  ProjectName:
    Type: String
    Default: cruddur-bake-image

  LogGroupPath:
    Type: String
    Default: /cruddur/codebuild/bake-service

  LogStreamName:
    Type: String
    Default: backend-flask

  CodeBuildImage:
    Type: String
    Default: aws/codebuild/amazonlinux2-x86_64-standard:4.0

  CodeBuildComputeType:
    Type: String
    Default: BUILD_GENERAL1_SMALL

  CodeBuildTimeoutMins:
    Type: Number
    Default: 10

  BuildSpec:
    Type: String
    Default: backend-flask/buildspec.yml

  ArtifactBucketName:
    Type: String
    Description: S3 bucket used by CodePipeline for build input and output artifacts

Resources:
  CodeBuildLogGroup:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref LogGroupPath
      RetentionInDays: 30

  CodeBuildRole:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${ProjectName}ECR"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'
              - Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:PutImage
                  - ecr:BatchGetImage
                  - ecr:GetDownloadUrlForLayer
                Resource: !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/*"
        - PolicyName: !Sub "${ProjectName}Logs"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${LogGroupPath}:*"
        - PolicyName: !Sub "${ProjectName}Artifacts"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                Resource: !Sub "arn:aws:s3:::${ArtifactBucketName}/*"
              - Effect: Allow
                Action:
                  - s3:GetBucketLocation
                  - s3:ListBucket
                Resource: !Sub "arn:aws:s3:::${ArtifactBucketName}"

  CodeBuildProject:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      ServiceRole: !GetAtt CodeBuildRole.Arn
      TimeoutInMinutes: !Ref CodeBuildTimeoutMins
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: !Ref CodeBuildComputeType
        Image: !Ref CodeBuildImage
        Type: LINUX_CONTAINER
        PrivilegedMode: true
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: !Ref LogGroupPath
          StreamName: !Ref LogStreamName
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              commands:
                - echo "cd into $CODEBUILD_SRC_DIR/backend-flask"
                - cd $CODEBUILD_SRC_DIR/backend-flask
                - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $IMAGE_URL
            build:
              commands:
                - echo Build started on `date`
                - echo Building the Docker image...
                - sed -i 's|387543059434.dkr.ecr.ca-central-1.amazonaws.com/cruddur-python:3.10-slim-buster|python:3.10-slim|g' Dockerfile.prod
                - docker build -f Dockerfile.prod -t $IMAGE_REPO_NAME:$IMAGE_TAG .
                - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_URL/$IMAGE_REPO_NAME:$IMAGE_TAG
            post_build:
              commands:
                - echo Build completed on `date`
                - echo Pushing the Docker image..
                - docker push $IMAGE_URL/$IMAGE_REPO_NAME:$IMAGE_TAG
                - cd $CODEBUILD_SRC_DIR
                - printf "[{\"name\":\"$CONTAINER_NAME\",\"imageUri\":\"$IMAGE_URL/$IMAGE_REPO_NAME:$IMAGE_TAG\"}]" > imagedefinitions.json
          env:
            variables:
              AWS_ACCOUNT_ID: 225442939245
              AWS_DEFAULT_REGION: eu-west-2
              CONTAINER_NAME: backend-flask
              IMAGE_URL: 225442939245.dkr.ecr.eu-west-2.amazonaws.com
              IMAGE_REPO_NAME: backend-flask
              IMAGE_TAG: latest
          artifacts:
            files:
              - imagedefinitions.json

Outputs:
  CodeBuildProjectName:
    Value: !Ref CodeBuildProject
  CodeBuildProjectArn:
    Value: !GetAtt CodeBuildProject.Arn
